# Generated by Django 5.2.6 on 2026-05-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('school_fees', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('other_fees', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('amount_requested', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('reduction_rate', models.FloatField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='academics.studentenrollment')),
            ],
            options={
                'verbose_name': 'Tranche de paiement',
                'ordering': ['order'],
            },
        ),
    ]
