# Generated by Django 6.0.6 on 2026-07-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_lessonentry'),
        ('finance', '0002_paymenttranche_is_bank_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttranche',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Rappel envoyé au parent'),
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('cantine', 'Cantine'), ('transport', 'Transport scolaire')], max_length=20, verbose_name='Service')),
                ('monthly_fee', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Tarif mensuel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Remarques (arrêt de bus, régime…)')),
                ('started_at', models.DateField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='academics.studentenrollment')),
            ],
            options={
                'verbose_name': 'Service annexe',
                'verbose_name_plural': 'Services annexes',
                'unique_together': {('enrollment', 'service_type')},
            },
        ),
    ]
