# Generated by Django 6.0.6 on 2026-07-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_grade_cc_alter_grade_ds_alter_grade_exam'),
        ('finance', '0003_paymenttranche_reminder_sent_extraservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPickupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('relationship', models.CharField(choices=[('grand_parent', 'Grand-parent'), ('oncle_tante', 'Oncle / Tante'), ('frere_soeur', 'Frère / Sœur majeur(e)'), ('nounou', "Nourrice / Garde d'enfant"), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Lien avec l'élève")),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('id_card_number', models.CharField(blank=True, max_length=30, verbose_name='N° CIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Autorisation active')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_persons', to='academics.studentenrollment')),
            ],
            options={
                'verbose_name': "Personne autorisée à récupérer l'élève",
                'verbose_name_plural': "Personnes autorisées à récupérer l'élève",
                'ordering': ['full_name'],
            },
        ),
    ]
