# Generated by Django 6.0.6 on 2026-07-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du père'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom et prénom du père'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du père'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la mère'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom et prénom de la mère'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de la mère'),
        ),
    ]
