# Generated by Django 6.0.6 on 2026-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_father_email_customuser_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_cin',
            field=models.CharField(blank=True, max_length=20, verbose_name="Numéro carte d'identité du père"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mother_cin',
            field=models.CharField(blank=True, max_length=20, verbose_name="Numéro carte d'identité de la mère"),
        ),
    ]
