# Generated by Django 6.0.6 on 2026-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_father_cin_customuser_mother_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='internal_contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contrat interne signé par les parents'),
        ),
    ]
