# Generated by Django 6.0.6 on 2026-07-09 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_internal_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parent_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Compte parent'),
        ),
    ]
