# Generated by Django 6.0.6 on 2026-07-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cin',
            field=models.CharField(blank=True, max_length=20, verbose_name="Numéro carte d'identité"),
        ),
    ]
