# Generated by Django 5.2.6 on 2026-05-12 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('carte_etudiant', "Carte d'etudiant"), ('cert_inscription', "Certificat d'inscription"), ('attest_presence', 'Attestation de presence'), ('attest_reussite', 'Attestation de reussite'), ('releve_notes', 'Releve des notes')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('ready', 'Pret'), ('delivered', 'Livré'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de document',
                'ordering': ['-created_at'],
            },
        ),
    ]
