# Generated by Django 5.2.6 on 2026-07-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Lettres', 'Lettres'), ('Economie et gestion', 'Economie et gestion'), ('Technique', 'Technique'), ('Informatique', 'Informatique'), ('Mathématiques', 'Mathématiques'), ('Sciences expérimentales', 'Sciences expérimentales')], max_length=100),
        ),
    ]
