# Generated by Django 6.0.6 on 2026-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classroom_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='max_installments',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de tranches autorisées'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cheque', 'Chèque'), ('traite', 'Traite bancaire')], max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
