# Generated by Django 6.0.6 on 2026-07-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentenrollment_max_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='subgroup',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
