# Generated by Django 6.0.6 on 2026-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('comptant', 'Comptant'), ('cheque', 'Chèque'), ('traite', 'Traite bancaire')], max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
