# Generated by Django 6.0.6 on 2026-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_studentenrollment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='label',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3')], max_length=2),
        ),
    ]
