# Generated by Django 6.0.6 on 2026-07-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_semester_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='classroom',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.studentenrollment'),
        ),
    ]
