# Generated by Django 6.0.6 on 2026-07-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_studentnote_classroom_alter_studentnote_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='controle',
        ),
    ]
