# Generated by Django 6.0.6 on 2026-07-28 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_grade_controle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_label', models.CharField(blank=True, max_length=200)),
                ('academic_year_label', models.CharField(blank=True, max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_history', to='academics.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcours élève',
                'verbose_name_plural': 'Parcours élèves',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
    ]
