# Generated by Django 6.0.6 on 2026-07-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_subject_teacher_tp_alter_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('start_hour', models.IntegerField()),
                ('session_type', models.CharField(choices=[('cours', 'Cours'), ('tp', 'TP')], default='cours', max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Créneau emploi du temps',
                'verbose_name_plural': 'Créneaux emploi du temps',
                'ordering': ['day', 'start_hour'],
                'unique_together': {('classroom', 'day', 'start_hour')},
            },
        ),
    ]
