# Generated by Django 6.0.6 on 2026-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='session_type',
            field=models.CharField(choices=[('cours', 'Cours'), ('tp', 'TP')], default='cours', max_length=10, verbose_name='Type de séance'),
        ),
    ]
