# Generated by Django 6.0.6 on 2026-07-28 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_absence_session_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de la séance')),
                ('content', models.TextField(verbose_name='Travail fait en classe')),
                ('homework', models.TextField(blank=True, verbose_name='Devoirs à faire')),
                ('homework_due', models.DateField(blank=True, null=True, verbose_name='Pour le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_entries', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_entries', to='academics.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cahier de textes',
                'verbose_name_plural': 'Cahier de textes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
