# Generated by Django 6.0.6 on 2026-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_courseresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cc',
            field=models.FloatField(blank=True, null=True, verbose_name='Orale'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='ds',
            field=models.FloatField(blank=True, null=True, verbose_name="Examen d'évaluation"),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.FloatField(blank=True, null=True, verbose_name='Examen final'),
        ),
    ]
